### ISSUE TITLE
Internal error: Internal error.

### ISSUE THREAD

**Issue by sergeyklay** [phpstan/docker-image#15]
Hello,

We use `phpstan/phpstan:latest` in our TeamCity CI.
So there is weird error `Internal error: Internal error.` without any clarification and description.

![screen shot 2017-10-25 at 4 22 43 pm](https://user-images.githubusercontent.com/1256298/32000896-d050a316-b9a0-11e7-8db0-04e73ab78099.png)

Steps to reproduce:
```
docker pull phpstan/phpstan

docker run --rm -v $PWD:/app phpstan/phpstan analyse --no-ansi -l max src/
```

Also as I can see `--no-ansi` doesn't work.

**Comment by ondrejmirtes** [comment]
Hi, thanks for the report. Can you run PHPStan just on `src/Client.php` and try to remove parts of the class until you're sure which line causes the internal error? And then post the minimal example which leads to the error?

**Comment by sergeyklay** [comment]
Ok

**Comment by sergeyklay** [comment]
Just removed all the body and ran `phpstan/phpstan` in my machine (I changed the namespace due privacy policy):

```php
namespace Vendor\Lib;

class Client
{
}
```

```
docker run --rm -v $PWD:/app phpstan/phpstan analyse --no-ansi -l max src/
  0/16 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  1/16 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   6%
  2/16 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  12%
  3/16 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  18%
  4/16 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  25%
  5/16 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  31%
  6/16 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  37%
  7/16 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  43%
  8/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
  9/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  56%
 10/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  62%
 11/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  68%
 12/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  75%
 13/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  81%
 14/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  87%
 15/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  93%


 16/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% ------ ---------------------------------
  Line   src/ClientOptions.php
 ------ ---------------------------------
         Internal error: Internal error.
 ------ ---------------------------------

 [ERROR] Found 1 error
```

But
```
docker run --rm -v $PWD:/app phpstan/phpstan analyse --no-ansi -l max src/Client.php
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] No errors
```

Note. I have no problem to run phpstan directly:

```
phpstan analyse --no-ansi -l max src/
  0/16 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  1/16 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   6%
  2/16 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  12%
  3/16 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  18%
  4/16 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  25%
  5/16 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  31%
  6/16 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  37%
  7/16 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  43%
  8/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
  9/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  56%
 10/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  62%
 11/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  68%
 12/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  75%
 13/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  81%
 14/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  87%
 15/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  93%
 16/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] No errors
```

**Comment by ondrejmirtes** [comment]
OK, I'll try to prepare some friendly debug options so we can pin this down. Give me some time, thanks :)

**Comment by sergeyklay** [comment]
Just located the weird behavior:

```php
namespace Vendor\Lib;

use Vendor\Lib\Traits\ConfigurableTrait;

class ClientOptions
{
    use ConfigurableTrait;

   // rest of code here
}
```

```
 ------ ---------------------------------
  Line   src/ClientOptions.php
 ------ ---------------------------------
         Internal error: Internal error.
 ------ ---------------------------------
```

Commenting `use ConfigurableTrait;` fix the issue.

**Comment by luispabon** [comment]
I'm having the same issue on Symfony controllers, caused by something in `Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait`, used in `Symfony\Bundle\FrameworkBundle\Controller\Controller` which is where my controllers are extending from.

Symfony 4.

**Comment by luispabon** [comment]
I'm trying to set up a repo with an example as I can't make the code I'm working on public, but having real trouble reproducing it...

**Comment by ondrejmirtes** [comment]
Please wait some time, I'll prepare a `debug` option that will make debugging this easier.

**Comment by luispabon** [comment]
roger that :+1:

**Comment by ondrejmirtes** [comment]
I just added a `--debug` option: https://github.com/phpstan/phpstan/commit/999d2c5304fcced7844d34f2b3102e8a296744fe

Can you retry running PHPStan with this commit (maybe wait for the Docker image to be rebuilt, should be done nightly) and post the output? Thanks!

**Comment by luispabon** [comment]
```
PHP Fatal error:  Uncaught PHPStan\ShouldNotHappenException: Internal error. in /home/development/projects/bbackend/vendor/phpstan/phpstan/src/Reflection/Php/PhpClassReflectionExtension.php:112
Stack trace:
#0 /home/development/projects/bbackend/vendor/phpstan/phpstan/src/Reflection/Php/PhpClassReflectionExtension.php(76): PHPStan\Reflection\Php\PhpClassReflectionExtension->createProperties(Object(PHPStan\Reflection\ClassReflection), true)
#1 /home/development/projects/bbackend/vendor/phpstan/phpstan/src/Reflection/ClassReflection.php(196): PHPStan\Reflection\Php\PhpClassReflectionExtension->getProperty(Object(PHPStan\Reflection\ClassReflection), 'serializer')
#2 /home/development/projects/bbackend/vendor/phpstan/phpstan/src/Type/ObjectType.php(41): PHPStan\Reflection\ClassReflection->getProperty('serializer', Object(PHPStan\Analyser\Scope))
#3 /home/development/TAB/racingp in /home/development/projects/bbackend/vendor/phpstan/phpstan/src/Reflection/Php/PhpClassReflectionExtension.php on line 112
```
Dumped the relevant variables:
```
				VarDumper::dump($hierarchyDistances);
				VarDumper::dump($annotationProperty->getDeclaringClass()->getName());
				VarDumper::dump($annotationProperty->getDeclaringClass());
```

Output: https://pastebin.com/RkMeMNBC
https://pastebin.com/RkMeMNBC

**Comment by luispabon** [comment]
Seems to be choking on the symfony serializer, maybe I can create a small project to recreate this

**Comment by luispabon** [comment]
Example here:
https://github.com/luispabon/phpstan-internal-error

  - clone
  - `composer install`
  - `vendor/bin/phpstan analyse src`

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan/commit/c0df313c7b82baa6d7bbf905df3d9f14f4db617c :)

**Comment by luispabon** [comment]
Works perfectly, thank you :+1:
